### PR TITLE
Added additional getter to GUIConsole

### PR DESCRIPTION
**Pull request by Blunderchips**
Added a getter for the console window.
Returns the actual scene2d window After the toFront method.

This change should give users more control over the physical GUI window.

### CODE REVIEW

**Comment by Blunderchips** [comment]
I amended the commit so it conforms as requested.

**Comment by StrongJoshua** [comment]
Sorry I messed up my explanation. I meant that this would be a function inherited from the Console Interface with an empty implementation in AbstractConsole and the correct implementation in GUIConsole (take a look at setHoverColor for example).  
I don't think the function should move the window to the front. The user can do that themselves when they get the Window object.

**Comment by Blunderchips** [comment]
I understand now, will make the change in the morning.

**Comment by Blunderchips** [comment]
Will do in a new PR.

**Pull request closed without merging**
