### PR TITLE
building with maven

### PR DESCRIPTION
**Pull request by born2snipe**
this should eliminate steps for getting the project loaded in an IDE and make it easy to access the example class.

I also removed the compiled classes and files in the target directory. It is generally bad practice to commit compiled code.

### CODE REVIEW

**Comment by StrongJoshua** [comment]
You removed the skin? How will it run without it?

**Comment by born2snipe** [comment]
If you are opening the project by the pom.xml these files will be copied over to the target directory.

You can always clone my project and see if it works for you or not.

**Comment by StrongJoshua** [comment]
This means that you would no longer be able to just use a compiled jar, but I guess that's fine. I should also be getting it to work as a true Gradle dependency (with maven central) soon too.

**Comment by born2snipe** [comment]
when you run `mvn clean verify` this will compile the classes, copy the resources, and bundle all those files into the JAR. So the "compiled jar" should still work as you expect.

**Comment by StrongJoshua** [comment]
Ok, I just don't understand where the skin is coming from. I assume it's part of a dependency (the basic gdx one, I think), but since I'm new to Maven and unsure of how the pom.xml file works, how does adding the skin as a resource without specifying its exact path within the dependency allow it to function for the console?

**Comment by born2snipe** [comment]
In maven when you mark a non-java file as a `resource` that means that file will be bundled in the artifact (ie. the jar). With the files in the jar you can just load the files using the classpath. That is how you are loading the skin now in the Console constructor.

**Comment by StrongJoshua** [comment]
Alright, I think I understand that, thanks!

**Pull request merged**
