### PR TITLE
Add APIs to select or deselect the Console

### PR DESCRIPTION
**Pull request by Dimitri0xff**
Deselecting the console is useful to be able to press game hotkeys while the console is still open.
Or just have a passive log window.
I would leave it to the game developer to implement selecting by mouse click or a hotkey.

### CODE REVIEW

**Comment by Dimitri0xff** [comment]
The mouse also shouldn't be captured when the Console is not selected. I'll fix that.
@StrongJoshua Am I heading in the right direction, or you have something different in mind?

**Comment by StrongJoshua** [comment]
Sorry that this is so terribly late, but hopefully a4cee5d6590951f14dc50af9aa749c1392a4cccf is what you wanted.

**Comment by Dimitri0xff** [comment]
Yes, thank you. Can you also add a console.select(), please?

**Comment by StrongJoshua** [comment]
Added in c2cc0015881fb2c69d1e7846afc400b3404953bb
Version 0.7.0 which includes that should be up soon.

**Comment by Dimitri0xff** [comment]
Great, thanks.

**Pull request closed without merging**
