### PR TITLE
Convenience api

### PR DESCRIPTION
**Pull request by piotr-j**
Added new api to clear the console and set maximum number of entries allowed. 

Refactored refresh() to not create new labels every time.

### CODE REVIEW

**Comment by StrongJoshua** [comment]
Smart move with improving the refresh function. I think I'll add an option to have unlimited entries.

**Comment by piotr-j** [comment]
Cool, i think ill implement custom position next. I dont like the
halfscreen stuff

**Comment by StrongJoshua** [comment]
Sure :) I was thinking of allowing the console to be movable and resizable (with constraints of course).

**Comment by StrongJoshua** [comment]
haha, I think we use different formatters, so merging often has many white-space changes :P

**Comment by piotr-j** [comment]
Yeah, Ill try to clean this up better next time.

**Pull request merged**
