### PR TITLE
Added api to change size and position of the console

### PR DESCRIPTION
**Pull request by piotr-j**
As above + removed unnecessary Vector3 creation.

Im not certain about param checks for new apis, any input?

### CODE REVIEW

**Comment by StrongJoshua** [comment]
I'm not sure what you mean by "param checks". Do you mean throwing IllegalArgumentException for bad parameters?

**Comment by piotr-j** [comment]
Yes, its arguable what can be considered bad. Size probably shouldnt be negative, but if it is bigger than screen is that an error? Position is similar in this regard.

**Comment by StrongJoshua** [comment]
Yes, negatives should not be allowed, and for size/position anything above 100% should error too. Ideally it would check if the console would go outside of the screen (for example, size percent width of 50 and position percent x position of 60) and then give an illegal argument or auto-resize to fit. I can't work on that now, but when I get back home I'll implement it!

**Comment by StrongJoshua** [comment]
I added some basic error throws, check my latest commit.

**Pull request merged**
