### PR TITLE
GUI Console Constructor with a Stage

### PR DESCRIPTION
**Pull request by Blunderchips**
Added a new constructor in the GUI Console class that accepts a Stage as a parameter. There needs to be some way to attach the console to a pre-existing stage, rather than create a new stage. At the moment, whenever a new GUI console is instantiated a new Stage is created. For projects that already have a Stage, there should be some way to make the console use that Stage. 

I would suggest creating a new constructor in the GUI Console class that accepts a Stage as a parameter.

### CODE REVIEW

**Comment by StrongJoshua** [comment]
Why do you think this is necessary? Everything already works even when there is an existing stage. The console uses an input multiplexer to manage input events, which is the only conflict that can really arise.

**Comment by Blunderchips** [comment]
If there is an existing stage why not make use of it? If for no other reason, consistency's sake.

**Comment by StrongJoshua** [comment]
That would require a bit more adjusting than just adding a constructor. A lot of the resizing of the console is managed by the stage it is in.

**Comment by StrongJoshua** [comment]
No follow-up. Closing this issue.

**Pull request closed without merging**
