### PR TITLE
Makes execCommand() public

### PR DESCRIPTION
**Pull request by saltares**
This would allow developers to read a set of commands from a file at run them at startup, very much like a `.bashrc` file.

### CODE REVIEW

**Comment by saltares** [comment]
Thanks!

**Comment by StrongJoshua** [comment]
Doing that now. Should be up soon.

**Comment by saltares** [comment]
Thanks a lot, appreciate it.

**Comment by StrongJoshua** [comment]
I'm presently having some difficulties with GPG, so apologies about this taking longer than expected.

**Comment by saltares** [comment]
No worries! Simply let me know here or is there a Twitter account/blog I should follow?

**Comment by StrongJoshua** [comment]
Well you can always check my website: http://strongjoshua.com/projects/games/in-game_console
But I've figured it out and the plugin has been updated to 0.3.3 which you can now download from maven.

**Comment by saltares** [comment]
Awesome, cheers.

**Pull request merged**
